### PR TITLE
Za theory

### PR DESCRIPTION
**Pull request by OlivierBondu**
@alesaggio

### CODE REVIEW

**Comment by OlivierBondu** [comment]
there are files produced when running the code. I added them here because, well, why not, this way they are bookkept elsewhere than my own area

**Comment by alesaggio** [comment]
ok, thanks a lot!

**Comment by alesaggio** [comment]
But apparently I don't have write access to this repo so I can't merge it...

**Comment by OlivierBondu** [comment]
indeed, I fixed the settings for the next time :)

**Pull request merged**
